2022-11-06 06:40:19,347 [INFO @ script_host.py:setup:69] 22920 - install import hook/path
2022-11-06 06:40:19,349 [INFO @ script_host.py:setup:74] 22920 - redirect sys.stdout and sys.stderr
2022-11-06 06:40:20,632 [WARNING @ session.py:handler:200] 22920 - error response from request 'python_execute ['import clang', 1, 1]': Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pynvim/plugin/script_host.py", line 95, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'clang'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pynvim/msgpack_rpc/session.py", line 195, in handler
    rv = self._request_cb(name, args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pynvim/api/nvim.py", line 210, in filter_request_cb
    result = request_cb(name, args)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pynvim/plugin/host.py", line 124, in _on_request
    rv = handler(*args)
         ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pynvim/plugin/host.py", line 102, in _wrap_function
    return fn(*args)
           ^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pynvim/plugin/script_host.py", line 97, in python_execute
    raise ErrorResponse(format_exc_skip(1))
pynvim.msgpack_rpc.session.ErrorResponse: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'clang'

